title: Phil Romig
description: Associate Teaching Professor
remote_theme: ankitsultana/researcher@gem

url: "https://promig3.github.io/"
baseurl: ""

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

# The 'nav:' section must look EXACTLY like this:
nav:
  - name: "About"
    link: "/"
  - name: "Contact"
    link: "/contact"
